### ISSUE TITLE
vue服务部署报错

### ISSUE THREAD

**Issue by JJLAAA** [DvcLAB/dockerhub#55]
## 报错日志
```
rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 124.115.222.148, server: ai.dvclab.com, request: "GET / HTTP/1.1", host: "ai.dvclab.com"
```
## 日志分析
- try_files指令的含义是在指定路径无法得到有效解析是，将请求rewrite到另外的指定的请求路径，但是如果指定的路径也无法得到有效解析，并且指定路径与之前的路径被同一个location处理，就会进入死循环
## 解决方法
- 暂时可以通过重启openresty解决
- 更改配置文件
```conf
location / {
          root /etc/nginx/lab;
          index index.html;
          try_files $uri $uri/ /index.html;
     }
```
- 修改GitHub Actions yaml配置文件
```yaml
name: VUE-CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 第一步：下载源码（CI/CD拉取代码到自己的本地）
      - name: Checkout
        uses: actions/checkout@master
      - name: set up node env
        uses: actions/setup-node@master
      - name: Installing project dependencies
        run: yarn
      - name: Building the project
        run: npm run build
      # 使用ssh链接服务器，清空旧的部署
      - name: Deploy
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /opt/dvclab/
            mkdir -p /opt/dvclab/
      # 拷贝打包好的文件
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "./dist/"
          target: "/opt/dvclab/"
      # 重启openresty服务
      - name: Restart
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: docker restart openresty

```
## 参考
1. [vue部署](https://cli.vuejs.org/zh/guide/deployment.html#docker-nginx)
2. [What does this nginx error “rewrite or internal redirection cycle” mean?](https://serverfault.com/questions/505098/what-does-this-nginx-error-rewrite-or-internal-redirection-cycle-mean)
3. [try_files参数的含义](https://zeven0707.github.io/2019/09/22/nginx%20try_files%E5%8F%82%E6%95%B0%E5%90%AB%E4%B9%89/)
